### ISSUE TITLE
protected setCollisionFlags

### ISSUE THREAD

**Issue by YanisBDF** [stephengold/Libbulletjme#1]
Hello, I want to add a collision flag to my PhysicsRigidBody but I can't beacause the method setCollisionFlag is protected, same for setActivationState.

**Comment by stephengold** [comment]
There's a PhysicsRigidBody.setContactResponse() method. Do you have some other reason to modify the collision flags?

There's a PhysicsCollisionObject.activate() method and a PhysicsRigidBody.setEnableSleep() method. Do you have some other reason to modify the activation state?

**Comment by YanisBDF** [comment]
I want to add an activation state because, when I spawn a stack of cube, they switch to "active tag" to "wants desactivation" and finally to "island sleeping" and when I kill a cube in the bottom of the stack, the others won't fall.

**Comment by stephengold** [comment]
After you kill the bottom cube you should invoke activate() on any bodies that might be affected by the change. That should wake them up (if they're sleeping) and allow them to fall.

**Comment by stephengold** [comment]
@YanisBDF Are the existing methods sufficient for your needs? If they are, I'll close this issue.

**Comment by YanisBDF** [comment]
Yes ! Thanks !
