### ISSUE TITLE
Latest versions does not exist in maven

### ISSUE THREAD

**Issue by tmvkrpxl0** [stephengold/Libbulletjme#10]
I decided to use double precision of this library, but it seems like they don't exist in maven yet. Could you upload them to maven?

**Comment by tmvkrpxl0** [comment]
Building project with latest library fails as it cannot find it

**Comment by YanisBDF** [comment]
Mr Gold surely knows this. You just have to be patient

**Comment by tmvkrpxl0** [comment]
I see

**Comment by stephengold** [comment]
It was 3:30 am here, and I needed to sleep. I'm working on the upload now.

**Comment by stephengold** [comment]
In the process of uploading 12.2.1, I discovered that 12.1.1 had never been uploaded! That was an oversight on my part, for which I apologize. I'm uploading both releases right now.

**Comment by stephengold** [comment]
Maven artifacts for both 12.1.1 and 12.2.1 should be available from MavenCentral now.

**Comment by tmvkrpxl0** [comment]
Thank you
