### ISSUE TITLE
Mac M1 support

### ISSUE THREAD

**Issue by riccardobl** [stephengold/Libbulletjme#15]
M1 support should be available in gradle since version 7.
Bullet should compile and work, since it is already compatible with linux arm64, my understanding is that the build script needs to be modified to include a target for
```
 architecture 'aarch64'
 operatingSystem 'osx'
```
I don't know how to do it, but if someone does i can test.

**Comment by stephengold** [comment]
Indeed, I was planning to investigate this after JME 3.5.0 is done.

A solution to this issue should ideally include continuous integration to build and test the native libraries, but none of my current CI providers (GitHub Actions, TravisCI, Appveyor) offers Mac-on-ARM hosts. Do you know one that does? (Preferably one that's free for open-source projects.)

Upgrading the project to Gradle 7 will be tricky. I tried once before and gave up, so I hope it's not necessary.

**Comment by riccardobl** [comment]
> Do you know one that does? 

I don't, but x86_64 mac can crosscompile to arm64 (aarch64) if the target platform is provided, so i guess it will just work if configured in gradle.

**Comment by stephengold** [comment]
That's fine for building natives, but I also want to test them.

**Comment by stephengold** [comment]
I started my investigation in the new "gradle7" branch. Gradle 7 builds work fine (aside from some Gradle warnings) for all platforms except MacOSX_ARM64, which was skipped when I expected it to be built. I suspect that's because this project still uses the "cpp" plugin (incubated in Gradle 4) instead of the "cpp-library" plugin (from Gradle 5+). Probably the "cpp" plugin hasn't been updated to cross-compile using XCode.

Perhaps I can work around this without switching plugins...

**Comment by stephengold** [comment]
Got stuck on a Gradle crash:
```text
A problem occurred configuring root project 'Libbulletjme'.
> Exception thrown while executing model rule: NativeBinaryRules#assignTools(NativeBinarySpec, NativeToolChainRegistryInternal, ProjectLayout)
   > A problem occurred starting process 'command 'xcrun''
```

Will try migrating to the "cpp-library" plugin...

**Comment by stephengold** [comment]
Apparently Gradle v7.3.3 only knows 2 values for `class MachineArchitecture`: `X86` and `X86_64`!

**Comment by stephengold** [comment]
Thanks for the link to issue 989.

I'm still pursuing multiple approaches. I've been using Xcode 13.2.1.

**Comment by stephengold** [comment]
I've found a mechanism in the "cpp" plugin to inject command-line args into Gcc and Clang toolchains, like so:
```groovy
        clangArm64(Clang) {
            target('MacOS_ARM64') {
                cppCompiler.arguments('-arch arm64')
                linker.arguments('-arch arm64')
            }
        }
```

The catch is that the "cpp" plugin doesn't allow the macOS hosts I'm using to build for target platforms with "arm64" or "aarch64" architecture, though it allows them to build for both "x86" and "x86_64". "cpp" doesn't place such restrictions on Linux hosts.

**Comment by stephengold** [comment]
> I've found a mechanism

Actually that doesn't work. Cross-compiling in Gradle is hard, especially for me with my ignorance of the Groovy language.

I'll add a target to "build.gradle" so you can try building your own natives on a Mac M1. However, I can't guess when pre-built native libraries will be available.

**Comment by stephengold** [comment]
I discovered a 3rd-party plugin that might help: https://docs.nokee.dev

**Comment by stephengold** [comment]
Native libraries for MacOSX_ARM64 became available on 2 March 2022, with the release of Libbulletjme 14.0.0 .
They were added to Minie at 04178cf5cd15e8200088e4cd4390d90723567c01 .
Support for MacOSX_ARM64 platforms became generally available on 20 March 2022, with the release of Minie v4.8.0 .
Note that JME v3.5.1-stable (or later) is required.
