### ISSUE TITLE
java.lang.NoClassDefFoundError: com/simsilica/mathd/Matrix3d

### ISSUE THREAD

**Issue by neo-expert** [stephengold/Libbulletjme#20]
For some reason with the latest version I am getting this Exception:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/simsilica/mathd/Matrix3d
	at com.jme3.bullet.util.NativeLibrary.countThreads(Native Method)
	at com.jme3.bullet.PhysicsSpace.<init>(PhysicsSpace.java:229)
	at com.jme3.bullet.PhysicsSpace.<init>(PhysicsSpace.java:199)
```

**Comment by stephengold** [comment]
One possible cause would be using an older native library with a newer Java library. Please make sure you've downloaded natives that correspond to the version you're using.

If that doesn't solve the issue, then I suggest you provide detailed instructions for reproducing the exception: a short, self contained, compilable example, including the versions of both libraries.

**Comment by stephengold** [comment]
@neo-expert Any update on this?

**Comment by neo-expert** [comment]
Ah it has resolved itself for some reason. I just recloned the project and the problem was gone.

**Comment by stephengold** [comment]
Thanks for the update. Let me know if the problem returns.
