### ISSUE TITLE
where is CollisionShapeFactory?

### ISSUE THREAD

**Issue by CientistaVuador** [stephengold/Libbulletjme#27]
in the library tutorials on automated decomposition (https://stephengold.github.io/Libbulletjme/lbj-en/English/shape.html#_automated_decomposition) there is a class called CollisionShapeFactory being used in the example but it does not seem to exist in the library.

**Comment by stephengold** [comment]
@CientistaVuador Thank you for bringing this inconsistency to my attention.

When I copied over the tutorials from my *other* physics project, I needed to make numerous adaptations. Apparently I missed one. I'm sorry about that.

There's no `CollisionShapeFactory` in Libbulletjme, so I should delete all references to it.

I'll leave this issue open until the tutorials are corrected.

**Comment by CientistaVuador** [comment]
thanks

**Comment by stephengold** [comment]
Solved!
