### ISSUE TITLE
Create a method in MeshCollisionShape to get a triangle

### ISSUE THREAD

**Issue by CientistaVuador** [stephengold/Libbulletjme#28]
I need to get the normal of a triangle in a MeshCollisionShape using the partIndex() and triangleIndex() from the sweep test result but I don't see any way to do it without using reflection and getting the CompoundMesh directly, the normal from the sweep test result is not accurate as you can see here: https://pybullet.org/Bullet/phpBB3/viewtopic.php?t=3538

**Comment by stephengold** [comment]
Thanks for raising this issue. I'll investigate.

**Comment by CientistaVuador** [comment]
thanks

**Comment by stephengold** [comment]
I propose to add 2 public methods to `MeshCollisionShape`:
```java
    /**
     * Count how many submeshes are in the mesh.
     *
     * @return the count (&ge;0)
     */
    public int countSubmeshes() {
        //...
    }

    /**
     * Access the specified submesh.
     *
     * @param index the index of the desired submesh (in the order the submeshes
     * were added, &ge;0)
     * @return the pre-existing instance (not null)
     */
    public IndexedMesh getSubmesh(int index) {
        //...
    }
```

That should provide sufficient access to avoid any need for reflection in this use case.

And since `GImpactCollisionShape` potentially has the same issue, I'll add similar methods there.

Sound good?

**Comment by CientistaVuador** [comment]
yes

**Comment by CientistaVuador** [comment]
thanks

**Comment by stephengold** [comment]
@CientistaVuador: Please test whether version 20.2.0 solves this issue for you.

**Comment by CientistaVuador** [comment]
I tested it, works fine
