### ISSUE TITLE
how to push object?

### ISSUE THREAD

**Issue by CrazyWords1** [stephengold/Libbulletjme#29]
I created a sphere, when I run the test scene, the sphere drops and interacts with the colliders, everything is great in that, but when I try to apply (force) to the sphere, nothing happens. What i do wrong?
P.S ( applyCentralImpulse(new Vector3f(-25f, 0f, 0f)) )

**Comment by stephengold** [comment]
@CrazyWords1 In general, `applyCentralImpulse()` ought to have some effect on the sphere's motion. I wonder about the sphere's mass and radius. Can you provide a simple test case?

**Comment by stephengold** [comment]
I verified that `applyCentralForce()` works as expected using tutorial code, specifically [HelloRigidBody](https://github.com/stephengold/LbjExamples/blob/master/apps/src/main/java/com/github/stephengold/lbjexamples/apps/HelloRigidBody.java).

I don't see any major problems with your code, though it seems strange to update every 50 ms while advancing the physics by only 10 ms.

I wonder what would happen if you increased the magnitude of the impulse by 10x. Another debugging approach would be to print the velocity of the sphere after each physics update.

**Comment by stephengold** [comment]
Between v20.2.0 and v21.0.0 there were incompatible changes to the API the JVM library uses to "talk to" the native library. If you upgrade one, you must upgrade the both. The warning indicates you somehow failed to do so.

**Comment by stephengold** [comment]
I'm glad!
