### ISSUE TITLE
[ Question ] - How does this library/engine handle spatial partitioning?

### ISSUE THREAD

**Issue by boxic** [stephengold/Libbulletjme#30]
Sorry if this is an inappropriate place to ask questions rather than file reports or feature requests, but I was just curious how this library/engine handles spatial partitioning - put simpler, how does the library/engine ensure rigid bodies only check for collisions against objects near them? Purely wanting to learn how it works! is there a specific tree structure it uses?

**Comment by stephengold** [comment]
JMonkeyEngine's scene graph is an acyclic directed graph: a tree of spatials, with meshes at the leaves. It gives you the flexibility to organize each scene spatially, if you wish. Whatever scene-graph organization you choose, spatial culling is performed using bounding volumes, either axis-aligned bounding boxes (AABBs) or bounding spheres, at each level of the graph.

JME is a volunteer-run project with an active and welcoming community, but we don't congregate here at GitHub. This is our tracker for bugs and enhancements. If you have (further) questions about how JME works, the best forum for them would be [our Discourse hub](https://hub.jmonkeyengine.org/).

**Comment by boxic** [comment]
thank you for the response!

**Comment by stephengold** [comment]
Re-reading this, I just realized that boxic probably *wasn't* asking about JMonkeyEngine, as I hastily assumed.
Oops!

**Comment by boxic** [comment]
Yeah I was talking about Bullet I think

**Comment by stephengold** [comment]
Bullet implements 2 broadphase collision algorithms:
1. incremental 3-D sweep and prune
2. dynamic bounding-volume hierarchy based on AABB

You basically select one or the other when the physics space is created.

I haven't studied them in detail, but I can point you to the C++ code.

**Comment by boxic** [comment]
Ah okay, that's much more insightful, thank you!
