### ISSUE TITLE
How to detect collisions of inner objects with the walls of a container?

### ISSUE THREAD

**Issue by Percibus** [stephengold/Libbulletjme#36]
I have sphere or capsule shapes that have other spheres or capsules inside. I need to bounce the inside objects against each other but also against the walls of the shape that contains them. Is there an easy way to do this? 

Since I didn't see a way to create “hollow” objects with other objects inside, the only way I can think of is to create two shapes for the container, one a little smaller than the other, and detect the collision when it comes out of the smaller shape, calculate the normal and make the bounce by hand with proper masking.

But with capsules it is a little more complicated than with spheres, and I don't know if it would be very accurate.

Is there a better way to do this? Thanks

**Comment by stephengold** [comment]
Off the top of my head, I suggest approximating the hollow outer shape as a `MeshCollisionShape` (assuming it doesn't have to move) or a `GImpactCollisionShape` (if it does). I haven't tried this, but I'm pretty sure it would work, assuming the inside objects have convex shapes.

You'd think Bullet might provide an easy way to reverse the normals of a convex shape, but if there is I'm unaware of it.

**Comment by Percibus** [comment]
It worked like a charm, thank you!
