### ISSUE TITLE
Using "compile" in build.gradle

### ISSUE THREAD

**Issue by tmvkrpxl0** [stephengold/Libbulletjme#8]
Hello, I am student and I want to use this for my project
I was looking for Physics engine I can use with java, and this is the perfect, it's being maintained

However there was one thing I want to mention about this project, AFAIK, `compile` in build.gradle is now deprecated and should be replaced with `implementation`
This is the source for this:https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-api-and-compile-in-gradle#44493379
I have tried to refresh my project after adding the physics engine, but it could not find method `compile` and was not able to compile it.
Had to replace `compile` to `implementation` for that, and now I can compile it.
Could you change it to `implementation` if there's no need to keep it `compile`?

**Comment by stephengold** [comment]
Thanks for reaching out to me.

The `implementation` dependency type was added to Gradle a couple years ago; it won't work for people using older versions of Gradle.

The `compile` dependency type was deprecated in Gradle v6, but still worked as of Gradle v6.9.1.  It only stopped working in Gradle 7, which was released in April.

I'll modify the README to provide instructions for both the old Gradle and the new Gradle.

**Comment by stephengold** [comment]
Solved in "master" branch at a3b8b33.
